import { chromium } from "/home/user/jurify/node_modules/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs";
const b = await chromium.launch({ executablePath: process.env.CHROME });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, storageState: "scratchpad/anuncio/sessao.json", deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
await p.goto("http://localhost:3000/relatorios", { waitUntil: "networkidle" }).catch(()=>{});
await p.waitForTimeout(3500);
const tab = p.getByRole("button", { name: "Comercial", exact: true }).first();
await tab.scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
await tab.click({ force: true });
await p.waitForTimeout(7000);
const larguraDoc = await p.evaluate(() => document.documentElement.scrollWidth);
console.log("largura do documento (390 = cabe):", larguraDoc);
const alvo = p.locator(':text("De qual anúncio veio o lead")').first();
await alvo.scrollIntoViewIfNeeded();
await p.waitForTimeout(600);
const box = await alvo.evaluate((el) => { let n=el; while(n && !(n.className && String(n.className).includes("rounded"))) n=n.parentElement; const r=(n||el).getBoundingClientRect(); return {x:r.x,y:r.y,width:r.width,height:r.height}; });
console.log("cartao:", JSON.stringify(box));
await p.screenshot({ path: process.argv[2], clip: { x: Math.max(0,box.x-6), y: Math.max(0,box.y-6), width: Math.min(box.width+12, 390), height: Math.min(box.height+12, 844) } });
await b.close();
