import { chromium } from "/home/user/jurify/node_modules/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs";
const b = await chromium.launch({ executablePath: process.env.CHROME });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, storageState: "scratchpad/anuncio/sessao.json", deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
await p.addInitScript(() => { try { localStorage.setItem("jurify:mobileCompleto", "1"); } catch {} });
await p.goto("http://localhost:3000/relatorios", { waitUntil: "networkidle" }).catch(()=>{});
await p.waitForTimeout(4500);
console.log("URL:", p.url());
const tab = p.getByRole("button", { name: "Comercial", exact: true }).first();
await tab.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await tab.click({ force: true });
await p.waitForTimeout(7000);
console.log("largura do documento (390 = cabe):", await p.evaluate(() => document.documentElement.scrollWidth));
const alvo = p.locator(':text("De qual anúncio veio o lead")').first();
console.log("cartao na tela:", await alvo.count());
await alvo.scrollIntoViewIfNeeded(); await p.waitForTimeout(600);
const box = await alvo.evaluate((el) => { let n=el; while(n && !(n.className && String(n.className).includes("rounded"))) n=n.parentElement; const r=(n||el).getBoundingClientRect(); return {x:r.x,y:r.y,width:r.width,height:r.height}; });
await p.screenshot({ path: process.argv[2], clip: { x: Math.max(0,box.x-6), y: Math.max(0,box.y-6), width: Math.min(box.width+12, 390), height: Math.min(box.height+12, 844) } });
console.log("cartao box:", JSON.stringify(box));
await b.close();
