import { chromium } from "/home/user/jurify/node_modules/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs";
const b = await chromium.launch({ executablePath: process.env.CHROME });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, storageState: "scratchpad/anuncio/sessao.json" });
const p = await ctx.newPage();
await p.goto("http://localhost:3000/relatorios", { waitUntil: "networkidle" }).catch(() => {});
await p.waitForTimeout(4000);
console.log("URL:", p.url());
const btns = await p.locator("button").allTextContents();
console.log("botões:", btns.filter(Boolean).map(s => s.trim().slice(0, 28)).slice(0, 25).join(" | "));
await b.close();
